version: "3.9"

services:
  db:
    container_name: db_container
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - postgres
  web:
    container_name: django_container
    build: .
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db
    networks:
      - postgres

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   env_file:
  #     - .env
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin

  #   ports:
  #     - "${PGADMIN_PORT}:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped
  #   depends_on:
  #     - db

networks:
  postgres:
    driver: bridge

volumes:
    db:
    pgadmin:
    web: